# Generated by Django 5.2.12 on 2026-05-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
        ('staff', '0005_staffshiftassignment_end_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hospital', 'code'), name='department_hospital_active_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hospital', 'code'), name='designation_hospital_active_code_uniq'),
        ),
    ]
