# Generated by Django 5.0.7 on 2026-04-25 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0002_ipdadmission_department'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='ipd_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='IPDAdmissionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_admission_sequences', to='shared.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'year')},
            },
        ),
    ]
