# Generated by Django 5.0.7 on 2026-05-15 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0005_ipdadmission_room_rent_daily_charge_override'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='shared.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='ipd.scheme'),
        ),
        migrations.AddConstraint(
            model_name='scheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hospital', 'name'), name='scheme_hospital_active_name_uniq'),
        ),
    ]
