"""Shared discharge summary field lists for catalog and templates."""

DISCHARGE_TEXT_FIELDS = [
    "summary_notes",
    "treatment_given",
    "condition_at_discharge",
    "medications_on_discharge",
    "follow_up_advice",
    "reason_for_admission",
    "diagnosis",
    "allergies",
    "procedure_surgery",
    "medical_history",
    "physical_examination",
    "investigations",
    "course_in_hospital",
    "diet_advice",
    "activity_advice",
    "warning_signs",
    "chief_complaints",
    "co_morbidities",
    "family_history",
    "personal_history",
    "complications_during_stay",
    "blood_transfusion_details",
    "implants_used",
    "indwelling_devices_on_discharge",
    "vaccination_given",
    "wound_care_instructions",
    "operative_findings",
    "intra_op_complications",
    "referral_reason",
    "cause_of_death",
    "surgeon_name",
    "assistant_name",
    "anaesthetist_name",
    "anaesthesia_type",
    "referred_to_facility",
    "treating_consultant",
    "consultant_registration_no",
    "rmo_signed_by",
    "follow_up_doctor",
    "follow_up_department",
    "notified_to",
    "abha_id",
    "insurance_provider",
    "tpa_name",
    "policy_number",
    "claim_number",
    "attendant_counselled_by",
]

DISCHARGE_CHOICE_FIELDS = [
    "discharge_type",
    "discharge_status",
    "mode_of_admission",
]

DISCHARGE_VITAL_FIELDS = ["bp", "pulse", "spo2", "temp", "weight", "rbs"]

DISCHARGE_CHILD_CATALOG_FIELDS = [
    "procedure_name",
    "test_name",
    "surgeon_name",
    "assistant_name",
    "anaesthetist_name",
    "anaesthesia_type",
]

DISCHARGE_TEMPLATE_EXCLUDE_FIELDS = {
    "admission",
    "hospital",
    "total_billed",
    "total_paid",
    "outstanding_balance",
    "discharge_date",
    "discharge_time",
    "next_follow_up_date",
    "stitch_removal_date",
    "surgery_date",
    "time_of_death",
    "is_draft",
    "created_at",
    "updated_at",
    "id",
}
