# Generated by Django 5.0.7 on 2026-04-22

import django.utils.timezone
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyCase",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=200)),
                ("contact", models.CharField(blank=True, default="", max_length=40)),
                ("complaint", models.TextField(blank=True, default="")),
                ("triage", models.CharField(choices=[("red", "Red"), ("yellow", "Yellow"), ("green", "Green")], default="yellow", max_length=10)),
                ("status", models.CharField(choices=[("waiting", "Waiting"), ("attended", "Attended"), ("admitted", "Admitted")], db_index=True, default="waiting", max_length=20)),
                ("arrived_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("attended_at", models.DateTimeField(blank=True, null=True)),
                ("admitted_at", models.DateTimeField(blank=True, null=True)),
                ("admitted_bed", models.CharField(blank=True, default="", max_length=60)),
                ("charge_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("charge_invoice_no", models.CharField(blank=True, default="", max_length=80)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="emergency_cases", to="shared.hospital")),
            ],
            options={
                "ordering": ("-arrived_at", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="emergencycase",
            index=models.Index(fields=["hospital", "status"], name="emergency_e_hospit_5fdf22_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencycase",
            index=models.Index(fields=["hospital", "triage"], name="emergency_e_hospit_a8b55f_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencycase",
            index=models.Index(fields=["hospital", "arrived_at"], name="emergency_e_hospit_b4114b_idx"),
        ),
    ]
