# Generated by Django 5.0.7 on 2026-04-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emergencycase',
            new_name='emergency_e_hospita_a1834f_idx',
            old_name='emergency_e_hospit_5fdf22_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencycase',
            new_name='emergency_e_hospita_12dafe_idx',
            old_name='emergency_e_hospit_a8b55f_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencycase',
            new_name='emergency_e_hospita_2f8754_idx',
            old_name='emergency_e_hospit_b4114b_idx',
        ),
    ]
