# Generated by Django 5.0.7 on 2026-04-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_treatmenttemplatecatalog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='treatmenttemplatecatalog',
            new_name='treatment_t_hospita_7501dd_idx',
            old_name='treatment_t_hospita_5d87d0_idx',
        ),
    ]
