# Generated by Django 5.0.7 on 2026-04-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
