# Generated by Django 5.0.7 on 2026-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billinginvoice_collection_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
