# Generated by Django 5.0.7 on 2026-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0011_opdvisit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
