# Generated by Django 5.0.7 on 2026-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_pharmacy',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark this hospital record as a pharmacy branch outlet. When active, this branch appears in the login-page pharmacy selector.'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pharmacy_display_name',
            field=models.CharField(blank=True, default='', help_text="Short name shown on the login page branch selector, e.g. 'Main Branch' or 'City Mall'. Falls back to the hospital name if left blank.", max_length=200),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_pharmacy', 'is_active'], name='shared_hosp_is_phar_3d1ff3_idx'),
        ),
    ]
