# Generated by Django 5.0.7 on 2026-04-25 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentslipsequence_paymenttransaction_slip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipsequence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='paymentslipsequence',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
