# Generated by Django 5.0.7 on 2026-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentslipsequence_created_at_and_more'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentquickservice',
            name='payments_pa_hospita_6ff6cc_idx',
        ),
        migrations.AddField(
            model_name='paymentquickservice',
            name='category',
            field=models.CharField(db_index=True, default='Custom', max_length=80),
        ),
        migrations.AddIndex(
            model_name='paymentquickservice',
            index=models.Index(fields=['hospital', 'is_active', 'category', 'sort_order'], name='payments_pa_hospita_fb8adc_idx'),
        ),
    ]
