# Generated by Django 5.0.7 on 2026-05-05 13:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_paymentquickservice_payments_pa_hospita_6ff6cc_idx_and_more'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQuickCategory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_quick_categories', to='shared.hospital')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['hospital', 'is_active', 'sort_order'], name='payments_pa_hospita_5b0355_idx'), models.Index(fields=['hospital', 'name'], name='payments_pa_hospita_ea4a14_idx')],
            },
        ),
    ]
