# Generated by Django 5.0.7 on 2026-05-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymenttransaction_public_slip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='public_slip_code',
        ),
    ]
