# Generated by Django 5.0.7 on 2026-06-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymenttransaction_collection_attribution'),
        ('payments', '0010_remove_paymenttransaction_public_slip_code'),
    ]

    operations = [
    ]
