# Generated by Django 5.0.7 on 2026-06-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_voided_field'),
        ('payments', '0011_merge_20260605_1331'),
    ]

    operations = [
    ]
