# Generated by Django 5.0.7 on 2026-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='activity_advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='course_in_hospital',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='diet_advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='investigations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='medical_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='physical_examination',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='procedure_surgery',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='reason_for_admission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='warning_signs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
