# Generated by Django 5.0.7 on 2026-04-28 01:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0002_dischargesummary_activity_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='abha_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='anaesthesia_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='anaesthetist_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='assistant_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='attendant_counselled_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='autopsy_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='blood_transfusion_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='cause_of_death',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='chief_complaints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='claim_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='co_morbidities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='complications_during_stay',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='consultant_registration_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='discharge_status',
            field=models.CharField(blank=True, choices=[('cured', 'Cured'), ('improved', 'Improved'), ('unchanged', 'Unchanged'), ('worsened', 'Worsened'), ('deceased', 'Deceased')], default='improved', max_length=20),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='discharge_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='discharge_type',
            field=models.CharField(blank=True, choices=[('routine', 'Routine'), ('lama', 'LAMA'), ('dama', 'DAMA'), ('referred', 'Referred'), ('transferred', 'Transferred'), ('death', 'Death'), ('absconded', 'Absconded')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='family_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='follow_up_department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='follow_up_doctor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='implants_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='indwelling_devices_on_discharge',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='intra_op_complications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='mode_of_admission',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('opd', 'OPD'), ('referral', 'Referral')], default='opd', max_length=20),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='notified_to',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='operative_findings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='patient_education_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='personal_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='policy_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='referral_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='referred_to_facility',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='rmo_signed_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='stitch_removal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='surgeon_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='surgery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='time_of_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='tpa_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='treating_consultant',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='vaccination_given',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='vitals_at_discharge',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='wound_care_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DischargeInvestigation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('lab', 'Lab'), ('imaging', 'Imaging')], default='lab', max_length=10)),
                ('test_name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, default='', max_length=120)),
                ('reference_range', models.CharField(blank=True, default='', max_length=120)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_rows', to='discharge.dischargesummary')),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DischargeMedication',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, default='', max_length=80)),
                ('route', models.CharField(blank=True, default='', max_length=40)),
                ('frequency', models.CharField(blank=True, default='', max_length=80)),
                ('duration', models.CharField(blank=True, default='', max_length=80)),
                ('instructions', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_rows', to='discharge.dischargesummary')),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
    ]
