# Generated by Django 5.0.7 on 2026-04-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0003_expand_summary_structured_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargemedication',
            name='rx_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
