# Generated by Django 5.0.7 on 2026-04-28 08:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0004_discharge_medication_rx_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSurgery',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('procedure_name', models.CharField(max_length=300)),
                ('surgeon_name', models.CharField(blank=True, default='', max_length=200)),
                ('assistant_name', models.CharField(blank=True, default='', max_length=200)),
                ('anaesthetist_name', models.CharField(blank=True, default='', max_length=200)),
                ('anaesthesia_type', models.CharField(blank=True, default='', max_length=120)),
                ('operative_findings', models.TextField(blank=True, default='')),
                ('intra_op_complications', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_rows', to='discharge.dischargesummary')),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
    ]
