# Generated by Django 5.0.7 on 2026-05-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0006_dischargesummary_is_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dischargesummary',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
    ]
