# Generated by Django 5.0.7 on 2026-04-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_medicinecategory_rule_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicine',
            name='inventory_m_hospita_c68958_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicinebatch',
            name='inventory_m_hospita_e858ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicinecategory',
            name='inventory_m_hospita_8c771c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockledger',
            name='inventory_s_hospita_a60b79_idx',
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='inventory_u_hospita_041fc6_idx',
        ),
    ]
