# Generated by Django 5.0.7 on 2026-04-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_medicinecategory_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicinecategory',
            new_name='inventory_m_hospita_9e2c78_idx',
            old_name='inventory_m_hospita_49d733_idx',
        ),
    ]
