# Generated by Django 5.0.7 on 2026-04-27 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_pharmacy_from_hospital(apps, schema_editor):
    Pharmacy = apps.get_model("pharmacy", "Pharmacy")
    Medicine = apps.get_model("inventory", "Medicine")
    MedicineBatch = apps.get_model("inventory", "MedicineBatch")
    MedicineCategory = apps.get_model("inventory", "MedicineCategory")
    MedicineReorderRule = apps.get_model("inventory", "MedicineReorderRule")
    StockLedger = apps.get_model("inventory", "StockLedger")
    Unit = apps.get_model("inventory", "Unit")

    hospital_ids = set()
    hospital_ids.update(Medicine.objects.exclude(hospital_id__isnull=True).values_list("hospital_id", flat=True).distinct())
    hospital_ids.update(MedicineBatch.objects.exclude(hospital_id__isnull=True).values_list("hospital_id", flat=True).distinct())
    hospital_ids.update(MedicineCategory.objects.exclude(hospital_id__isnull=True).values_list("hospital_id", flat=True).distinct())
    hospital_ids.update(Unit.objects.exclude(hospital_id__isnull=True).values_list("hospital_id", flat=True).distinct())
    hospital_ids.update(MedicineReorderRule.objects.exclude(hospital_id__isnull=True).values_list("hospital_id", flat=True).distinct())

    pharmacy_by_hospital = {}
    for hospital_id in hospital_ids:
        pharmacy = Pharmacy.objects.filter(hospital_id=hospital_id).order_by("created_at", "id").first()
        if pharmacy is None:
            pharmacy = Pharmacy.objects.create(
                id=uuid.uuid4(),
                hospital_id=hospital_id,
                name="Main Pharmacy",
                slug=f"main-pharmacy-{str(hospital_id).replace('-', '')[:10]}",
                is_active=True,
                display_name="Main Pharmacy",
            )
        pharmacy_by_hospital[hospital_id] = pharmacy.id

    for hospital_id, pharmacy_id in pharmacy_by_hospital.items():
        Medicine.objects.filter(hospital_id=hospital_id).update(pharmacy_id=pharmacy_id)
        MedicineBatch.objects.filter(hospital_id=hospital_id).update(pharmacy_id=pharmacy_id)
        MedicineCategory.objects.filter(hospital_id=hospital_id).update(pharmacy_id=pharmacy_id)
        MedicineReorderRule.objects.filter(hospital_id=hospital_id).update(pharmacy_id=pharmacy_id)
        Unit.objects.filter(hospital_id=hospital_id).update(pharmacy_id=pharmacy_id)

    # stockledger.hospital is already removed in this migration step; infer by medicine linkage.
    for medicine_id, pharmacy_id in Medicine.objects.values_list("id", "pharmacy_id"):
        StockLedger.objects.filter(medicine_id=medicine_id).update(pharmacy_id=pharmacy_id)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_medicine_inventory_m_hospita_c68958_idx_and_more'),
        ('pharmacy', '0012_pharmacy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockledger',
            name='hospital',
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='medicine_categories', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinereorderrule',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockledger',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_pharmacy_from_hospital, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('pharmacy', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together={('pharmacy', 'medicine', 'batch_no')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinecategory',
            unique_together={('pharmacy', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinereorderrule',
            unique_together={('pharmacy', 'medicine')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('pharmacy', 'code')},
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pharmacy', 'name'], name='inventory_m_pharmac_38be75_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['pharmacy', 'medicine', 'expiry_date'], name='inventory_m_pharmac_1d6811_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinecategory',
            index=models.Index(fields=['pharmacy', 'name'], name='inventory_m_pharmac_a3476e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['pharmacy', 'medicine', 'batch'], name='inventory_s_pharmac_4301b9_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['pharmacy', 'name'], name='inventory_u_pharmac_c3d370_idx'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicinebatch',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicinecategory',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicinereorderrule',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='hospital',
        ),
    ]
