# Generated by Django 5.0.7 on 2026-04-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_merge_20260427_2306'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS inventory_m_hospita_9e2c78_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='medicinecategory',
                    name='inventory_m_hospita_9e2c78_idx',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='medicinecategory',
            name='parent',
        ),
    ]
