# Generated by Django 5.0.7 on 2026-05-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_medicinecategory_parent_restored'),
        ('pharmacy', '0012_pharmacy_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicinecategory',
            unique_together={('pharmacy', 'parent', 'name')},
        ),
    ]
