# Generated by Django 5.2.14 on 2026-05-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_medicine_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='name_on_bill',
            field=models.CharField(blank=True, default='', help_text='Optional print name on customer invoice; falls back to nickname.', max_length=250),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(help_text='Internal nickname for pharmacy staff.', max_length=250),
        ),
    ]
