/** Central route paths for admin portal — all prefixed with /admin. */
export const ADMIN_ROUTES = {
  DASHBOARD: '/admin',
  PERMISSIONS: '/admin/permissions',
  PATIENTS: '/admin/patients',
  PATIENT_NEW: '/admin/patients/new',
  APPOINTMENTS: '/admin/appointments',
  BATCHES: '/admin/batches',
  DAILY_AVAILABILITY: '/admin/daily-availability',
  DEPARTMENTS: '/admin/departments',
  DESIGNATIONS: '/admin/designations',
  DOCTOR_PROFILES: '/admin/doctor-profiles',
  EMERGENCY_CONTACTS: '/admin/emergency-contacts',
  FOLLOW_UPS: '/admin/follow-ups',
  INVOICES: '/admin/invoices',
  IPD_ADMISSIONS: '/admin/ipd-admissions',
  MEDICINES: '/admin/medicines',
  OPD_VISITS: '/admin/opd-visits',
  PAYMENTS: '/admin/payments',
  SHIFTS: '/admin/shifts',
  SPECIALTIES: '/admin/specialties',
  STAFF: '/admin/staff',
  STOCK_LEDGERS: '/admin/stock-ledgers',
  TOKENS: '/admin/tokens',
  UNITS: '/admin/units',
  WEEKLY_SCHEDULES: '/admin/weekly-schedules',
  /** Legacy redirects */
  DOCTORS: '/admin/doctors',
  BILLING: '/admin/billing',
  LAB: '/admin/lab',
};
