# Generated by Django 5.0.7 on 2026-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_registration_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_salutation',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
