# Generated by Django 5.0.7 on 2026-04-22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_management", "0001_add_leave_approver"),
        ("shared", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceptionPortalSettings",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("default_city", models.CharField(blank=True, default="Jind", max_length=120)),
                ("default_state", models.CharField(blank=True, default="Haryana", max_length=120)),
                ("hospital_name", models.CharField(blank=True, default="Vardraan Hospital", max_length=200)),
                ("address", models.CharField(blank=True, default="Jind, Haryana, 126102", max_length=255)),
                ("pin_code", models.CharField(blank=True, default="126102", max_length=30)),
                ("phone", models.CharField(blank=True, default="+91-XXXXXXXXXX", max_length=40)),
                ("email", models.CharField(blank=True, default="info@vardraanhospital.com", max_length=120)),
                ("website", models.CharField(blank=True, default="www.vardraanhospital.com", max_length=200)),
                (
                    "default_doctor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_reception_portal_for_hospitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_portal_settings",
                        to="shared.hospital",
                    ),
                ),
            ],
        ),
    ]
