# Generated by Django 5.0.7 on 2026-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0002_receptionportalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionportalsettings',
            name='print_with_background',
            field=models.BooleanField(default=True),
        ),
    ]
