# Generated by Django 5.0.7 on 2026-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0003_receptionportalsettings_print_with_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionportalsettings',
            name='opd_fee_mode',
            field=models.CharField(choices=[('doctor', 'Doctor charges currently following'), ('slot', 'Slots wise')], default='doctor', max_length=10),
        ),
        migrations.AddField(
            model_name='receptionportalsettings',
            name='opd_fee_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
