# Generated by Django 5.0.7 on 2026-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0009_expand_opd_core_field_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='opd_visible_fields',
            field=models.JSONField(blank=True, default=list, help_text='Legacy hidden-field keys; prefer opd_field_config.'),
        ),
    ]
