# Generated by Django 5.0.7 on 2026-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0010_alter_receptionportalsettings_opd_visible_fields'),
        ('settings_management', '0010_opd_core_field_visit_date'),
    ]

    operations = [
    ]
