# Generated by Django 5.0.7 on 2026-04-27 05:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


DEFAULT_PHARMACY_ID = "1f88d8fb-de32-4ee8-a937-a0e619a87818"


def ensure_default_pharmacy(apps, schema_editor):
    Pharmacy = apps.get_model("pharmacy", "Pharmacy")
    Hospital = apps.get_model("shared", "Hospital")
    hospital_id = Hospital.objects.order_by("id").values_list("id", flat=True).first()
    if not hospital_id:
        return

    Pharmacy.objects.get_or_create(
        id=DEFAULT_PHARMACY_ID,
        defaults={
            "hospital_id": hospital_id,
            "name": "Main Pharmacy",
            "slug": "main-pharmacy",
            "is_active": True,
            "display_name": "Main Pharmacy",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_pharmacyoutletsettings_default_sale_discount_percent'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='pharmacypurchasechallan',
            name='pharm_pc_hosp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacypurchasechallan',
            name='pharm_pc_hosp_sup_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacysupplier',
            name='pharmacy_ph_hospita_8a5e91_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacysupplier',
            name='pharmacy_ph_hospita_85c9e0_idx',
        ),
        migrations.RemoveField(
            model_name='pharmacyinvoice',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='pharmacyoutletsettings',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='pharmacypurchasechallan',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='pharmacysupplier',
            name='hospital',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='shared.hospital'),
        ),
        migrations.RunPython(ensure_default_pharmacy, migrations.RunPython.noop),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_invoices', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyoutletsettings',
            name='pharmacy',
            field=models.OneToOneField(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_outlet_settings', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacypurchasechallan',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_purchase_challans', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='pharmacy',
            field=models.ForeignKey(default='1f88d8fb-de32-4ee8-a937-a0e619a87818', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_suppliers', to='pharmacy.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pharmacypurchasechallan',
            index=models.Index(fields=['pharmacy', 'purchase_date'], name='pharm_pc_hosp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacypurchasechallan',
            index=models.Index(fields=['pharmacy', 'supplier'], name='pharm_pc_hosp_sup_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysupplier',
            index=models.Index(fields=['pharmacy', 'name'], name='pharmacy_ph_pharmac_17a841_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysupplier',
            index=models.Index(fields=['pharmacy', 'is_active'], name='pharmacy_ph_pharmac_cebe36_idx'),
        ),
    ]
