# Generated by Django 5.0.7 on 2026-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_b2b_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyoutletsettings',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Medicines with total stock below this value are flagged as low stock.'),
        ),
    ]
