# Generated by Django 5.2.12 on 2026-05-27 04:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_pharmacy_billing_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinvoiceitem',
            name='free_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Complimentary base units (not taxed); stock deducts qty + free_qty.', max_digits=12),
        ),
    ]
