# Generated by Django 5.0.7 on 2026-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_split_b2b_b2c_outlet_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyoutletsettings',
            name='b2b_default_sale_gst_enabled',
            field=models.BooleanField(default=False, help_text='Default GST on/off when opening B2B sales.'),
        ),
        migrations.AlterField(
            model_name='pharmacyoutletsettings',
            name='b2c_default_sale_gst_enabled',
            field=models.BooleanField(default=False, help_text='Default GST on/off when opening B2C sales.'),
        ),
        migrations.AlterField(
            model_name='pharmacyoutletsettings',
            name='b2c_low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='B2C inventory low-stock alert threshold (base units).'),
        ),
    ]
