# Generated by Django 5.0.7 on 2026-06-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_alter_pharmacyoutletsettings_b2b_default_sale_gst_enabled_and_more'),
        ('pharmacy', '0025_backfill_snapshot_unit_cost'),
    ]

    operations = [
    ]
