# Generated by Django 5.0.7 on 2026-06-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_fix_zero_snapshot_unit_cost'),
        ('pharmacy', '0026_merge_20260613_1129'),
    ]

    operations = [
    ]
