# Generated by Django 5.0.7 on 2026-04-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

import apps.doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_add_pharmacy_branch_fields_to_hospital"),
        ("doctors", "0005_remove_doctorprofile_doctors_doc_departm_69367e_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPortalPreference",
            fields=[
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("followup_day_options", models.JSONField(default=apps.doctors.models.default_followup_days)),
                ("rx_default_day_options", models.JSONField(default=apps.doctors.models.default_rx_days)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="doctor_portal_preferences", to="shared.hospital")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="doctor_portal_preference", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="doctorportalpreference",
            index=models.Index(fields=["hospital", "user"], name="doctors_doc_hospita_7d1635_idx"),
        ),
    ]
