# Generated by Django 5.0.7 on 2026-04-27 10:35

from django.db import migrations, models

import apps.doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_doctorportalpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorportalpreference",
            name="dosage_pattern_options",
            field=models.JSONField(default=apps.doctors.models.default_dosage_pattern_options),
        ),
        migrations.AddField(
            model_name="doctorportalpreference",
            name="food_timing_options",
            field=models.JSONField(default=apps.doctors.models.default_food_timing_options),
        ),
    ]
