# Generated by Django 5.2.12 on 2026-05-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctorprofile_doctor_code_required_unique'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
        ('staff', '0005_staffshiftassignment_end_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specialty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hospital', 'code'), name='specialty_hospital_active_code_uniq'),
        ),
    ]
